window.onload = function () {
    document.querySelector('jqx-list-box').dataSource = [
           "Indian filter coffee",
           "Cortado",
           "Americano",
           "Cappuccino",
           "Bicerin",
           "Breve",
           "Galao",
           "Café au lait",
           "Caffé Corretto",
           "Caffé Latte",
           "Indian filter coffee",
           "Caffé macchiato",
           "Coffee milk",
           "Cafe mocha",
           "Cappuccino",
           "Carajillo",
           "Cappuccino",
           "Cuban espresso",
           "Espresso",
           "Eiskaffee",
           "The Flat White",
           "Café mélange",
           "Frappuccino",
           "Galao",
           "Greek frappé",
           "Iced Coffee﻿",
           "Instant coffee",
           "Café Crema",
           "Irish coffee",
           "Café Bombón",
           "Liqueur coffee",
           "Affogato"
    ];
}